### DISCUSSION TITLE
Which format for naming sections in `_quarto.yml`?

### DISCUSSION THREAD

**Discussion by stefaniebutland** [NASA-Openscapes/earthdata-cloud-cookbook#219] [Q&A] [answered]
In `_quarto.yml`, which of these 2 formats should we use consistently for naming sections? In recent Quarto refresh of Openscapes website I see Choice B used.

Choice A: as in https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/blob/1929b009407f758a9ae1a765849da6d7f8d4ecd4/_quarto.yml#L123

```
        contents: 
          - contributing/onboarding.qmd
          - contributing/setup.qmd
          - contributing/workflow.qmd
```

Choice B: as in https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/blob/1929b009407f758a9ae1a765849da6d7f8d4ecd4/_quarto.yml#L48

```
            contents:
              - text: "using Earthdata Search"
                href: how-tos/find-data/earthdata_search.md
              - text: "using code" 
                href: how-tos/find-data/programmatic.qmd
```
